export const motivationalQuotes = [
  "Trova ciò che ami e lascia che ti uccida. - Charles Bukowski",
  "Non arrenderti. Normalmente è l'ultima chiave del mazzo quella che apre la porta. - Charles Bukowski",
  "Alcune persone non impazziscono mai. Che vita veramente orribile devono vivere. - Charles Bukowski",
  "Se stai per provare, vai fino in fondo. Altrimenti, non iniziare nemmeno. - Charles Bukowski",
  "Il problema del mondo è che le persone intelligenti sono piene di dubbi, mentre le stupide sono piene di sicurezza. - Charles Bukowski",
  "Quello che conta di più è come cammini attraverso il fuoco. - Charles Bukowski",
  "La libertà è qualcosa che muore a meno che non venga usata. - Charles Bukowski",
  "Siamo qui per ridere delle probabilità e vivere le nostre vite così bene che la Morte tremerà nel prenderci. - Charles Bukowski",
  "A volte devi morire un po' dentro per poter rinascere e crescere. - Charles Bukowski",
  "La cosa peggiore per uno scrittore è sapere di un altro scrittore che è più bravo di lui. - Charles Bukowski",
  "Non è la grande cosa che fai, ma la piccola cosa che fai con grande amore. - Charles Bukowski",
  "Tutti vogliono salvare la terra; nessuno vuole aiutare la mamma a lavare i piatti. - Charles Bukowski",
  "Il genio potrebbe essere la capacità di dire una cosa profonda in modo semplice. - Charles Bukowski",
  "Ci sono peggiori crimini dell'aver bruciato libri. Uno di questi è non leggerli. - Charles Bukowski",
  "La cosa più bella della vita è che non c'è niente di sicuro tranne la morte. - Charles Bukowski",
  "Noi siamo qui per bere birra. Siamo qui per uccidere la guerra. Siamo qui per ridere del destino e vivere così bene che la morte tremerà nel prenderci. - Charles Bukowski",
  "L'arte è sopravvivenza. - Charles Bukowski",
  "Puoi battere un cavallo da corsa ma non puoi batterlo a scacchi. - Charles Bukowski",
  "La differenza tra una democrazia e una dittatura è che in una democrazia voti prima di obbedire agli ordini. - Charles Bukowski",
  "Ho bevuto per annegare i miei dolori, ma i bastardi hanno imparato a nuotare. - Charles Bukowski",
  "La cosa più difficile è essere se stessi in un mondo che cerca di renderti come tutti gli altri. - Charles Bukowski",
  "Non odio le persone, mi sento solo meglio quando non sono in giro. - Charles Bukowski",
  "Se vuoi sapere chi sono i tuoi amici, fatti arrestare. - Charles Bukowski",
  "La vita è una malattia mortale a trasmissione sessuale. - Charles Bukowski",
  "Scrivo per rimanere sano di mente. - Charles Bukowski",
  "Il talento è un dono, ma il carattere è una scelta. - Charles Bukowski",
  "La solitudine non è mai stata un problema per me, solo le persone lo sono. - Charles Bukowski",
  "Quello che la maggior parte delle persone chiama amore è solo chimica. - Charles Bukowski",
  "Non c'è niente di più deprimente di avere tutto. - Charles Bukowski",
  "La bellezza è niente senza la follia. - Charles Bukowski",
  "Ho sempre voluto essere qualcuno, ma avrei dovuto essere più specifico. - Charles Bukowski",
  "Il modo per creare arte è bruciare e distruggere le regole ordinarie. - Charles Bukowski",
  "La scrittura è qualcosa che fai da solo. È una professione per introversi che vogliono raccontarti una storia ma non vogliono guardarti negli occhi mentre lo fanno. - Charles Bukowski",
  "Dormo bene la notte perché so che ho fatto del mio meglio per rendere le cose peggiori per tutti. - Charles Bukowski",
  "Non cercare mai di essere migliore di qualcun altro. Impara da loro e poi sii te stesso. - Charles Bukowski",
  "Il problema è che pensiamo troppo, sentiamo troppo poco. - Charles Bukowski",
  "La cosa peggiore per un uomo è invecchiare senza diventare saggio. - Charles Bukowski",
  "Non ho mai incontrato un altro uomo che volessi essere. - Charles Bukowski",
  "La vera libertà è una cosa terribile e meravigliosa. - Charles Bukowski",
  "Più impari a conoscere le persone, più ami i cani. - Charles Bukowski",
  "La vita è troppo breve per non essere folli. - Charles Bukowski",
  "Non lasciarti distruggere da ciò che non puoi controllare. - Charles Bukowski",
  "Il tempo è la cosa più preziosa che un uomo può spendere. - Charles Bukowski",
  "La povertà è la peggiore forma di violenza. - Charles Bukowski",
  "Non importa quanto sei bravo, qualcuno sarà sempre migliore di te. - Charles Bukowski",
  "La vita inizia quando smetti di aspettare che inizi. - Charles Bukowski",
  "Nessuno può salvarti tranne te stesso. - Charles Bukowski",
  "L'intelligenza è la capacità di adattarsi al cambiamento. - Charles Bukowski",
  "Il fallimento è solo un'opportunità per ricominciare in modo più intelligente. - Charles Bukowski",
  "La normalità è una strada asfaltata: è comoda da percorrere, ma non ci crescono fiori. - Charles Bukowski",
  "Non sprecare il tuo tempo con spiegazioni: la gente sente solo quello che vuole sentire. - Charles Bukowski",
  "La cosa più coraggiosa che puoi fare è pensare con la tua testa. Ad alta voce. - Charles Bukowski",
  "Quello che mi piace di più è restare a casa e leggere un libro. - Charles Bukowski",
  "La vita è una serie di cani. - Charles Bukowski",
  "Non c'è niente di sbagliato nel non capire te stesso. - Charles Bukowski",
  "Il segreto della vita è non avere paura di essere ridicolo. - Charles Bukowski",
  "La creatività è permettere a te stesso di fare errori. L'arte è sapere quali tenere. - Charles Bukowski",
  "Non puoi battere la morte ma puoi batterla a morte nella vita, a volte. - Charles Bukowski",
  "La cosa più importante è continuare a muoversi, continuare a fare. - Charles Bukowski",
  "Niente è mai finito finché non smetti di provare. - Charles Bukowski",
  "La vita è una lunga serie di addii. - Charles Bukowski",
  "Non importa quanto male vanno le cose, c'è sempre qualcosa di peggio che potrebbe accadere. - Charles Bukowski",
  "La solitudine aggiunge bellezza alla vita. Ha un effetto speciale sulle albe e sui tramonti. - Charles Bukowski",
  "Il mondo è pieno di persone che vogliono dirti come vivere la tua vita. Non ascoltarle. - Charles Bukowski",
  "La cosa più difficile da fare è essere onesti con se stessi. - Charles Bukowski",
  "Non c'è niente di più triste di un giovane pessimista. - Charles Bukowski",
  "La vita è troppo breve per perdere tempo con persone che ti succhiano la felicità. - Charles Bukowski",
  "Il vero coraggio è vivere quando vuoi morire. - Charles Bukowski",
  "Non importa quanto sei ubriaco, non puoi sfuggire a te stesso. - Charles Bukowski",
  "La cosa migliore della vita è che non devi essere perfetto per essere meraviglioso. - Charles Bukowski",
  "Non c'è niente di più liberatorio che non fregarsene di quello che pensano gli altri. - Charles Bukowski",
  "La vita è una battaglia, ma vale la pena combatterla. - Charles Bukowski",
  "Il tempo guarisce tutto, tranne le ferite che non vuoi guarire. - Charles Bukowski",
  "Non puoi aspettare l'ispirazione. Devi andarle incontro con una mazza. - Charles Bukowski",
  "La cosa più importante nella vita è essere fedeli a te stesso. - Charles Bukowski",
  "Non c'è niente di più bello di una persona che ha superato l'inferno e ne è uscita con un sorriso. - Charles Bukowski",
  "La vita è troppo importante per essere presa sul serio. - Charles Bukowski",
  "Il problema con il mondo è che gli stupidi sono sicuri di sé, mentre gli intelligenti sono pieni di dubbi. - Charles Bukowski",
  "Non importa quanto sei giù, puoi sempre scendere più in basso. - Charles Bukowski",
  "La cosa più difficile è accettare che la vita non ha senso. - Charles Bukowski",
  "Non c'è niente di più triste di una vita non vissuta. - Charles Bukowski",
  "La libertà è essere te stesso senza chiedere il permesso. - Charles Bukowski",
  "Il vero amore è quando qualcuno accetta il tuo passato, sostiene il tuo presente e incoraggia il tuo futuro. - Charles Bukowski",
  "Non importa quanto sei solo, sei sempre in buona compagnia con un buon libro. - Charles Bukowski",
  "La cosa più importante è non smettere mai di imparare. - Charles Bukowski",
  "Non c'è niente di più potente di una mente che non ha paura di pensare. - Charles Bukowski",
  "La vita è una serie di scelte. Scegli saggiamente. - Charles Bukowski",
  "Il vero successo è essere felice con quello che hai. - Charles Bukowski",
  "Non importa quanto è buio, c'è sempre una luce da qualche parte. - Charles Bukowski",
  "La cosa più coraggiosa che puoi fare è essere vulnerabile. - Charles Bukowski",
  "Non c'è niente di più prezioso del tempo che passi facendo quello che ami. - Charles Bukowski",
  "La vita è troppo breve per vivere nei rimpianti. - Charles Bukowski",
  "Il vero potere è avere il controllo su te stesso. - Charles Bukowski",
  "Non importa quante volte cadi, l'importante è quante volte ti rialzi. - Charles Bukowski",
  "La cosa più importante è rimanere fedeli ai propri sogni. - Charles Bukowski",
  "Non c'è niente di più liberatorio che accettare se stessi per quello che si è. - Charles Bukowski",
  "La vita è un viaggio, non una destinazione. - Charles Bukowski",
  "Il vero coraggio è essere gentili in un mondo crudele. - Charles Bukowski",
  "Non importa quanto sei diverso, sei perfetto così come sei. - Charles Bukowski"
];

